name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'  
      uses: actions/checkout@v2
    
    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/devopsoh/api-user-java:${{ github.run_number }} -f apis/user-java/Dockerfile
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/devopsoh/api-user-java:${{ github.run_number }}

  task: AzureWebAppContainer@v1
        inputs:
          azureSubscription: '1a7a95d7-122f-4920-a3cb-b47515acefc9'
          appName: 'openhack06u2z0e9userjava'
          containers: ${{ secrets.REGISTRY_LOGIN_SERVER }}/devopsoh/api-user-java:${{ github.run_number }}
          deployToSlotOrASE: false
          resourceGroupName: 'openhack06u2z0e9rg'
          slotName: staging