# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths: apis/user-java

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file apis/user-java/pom.xml
    - name: Test
      run: mvn test -f apis/user-java/pom.xml
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
      - run: mvn -B package --file apis/user-java/pom.xml
      - run: mkdir apis/user-java/staging && cp apis/user-java/target/*.jar apis/user-java/staging
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: apis/user-java/staging