name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'  
      uses: actions/checkout@v2
    
    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: 
        docker build -t openhack06u2z0e9acr.azurecr.io/devopsoh/api-user-java:${{ github.run_number }} --build-arg build_version=${{ github.run_number}} -f apis/user-java/Dockerfile
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/api-user-java:${{ github.run_number }}